src/main/java/net/sourceforge/pebble/domain/BlogEntry.java
/*
 * Copyright (c) 2003-2011, Simon Brown
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   - Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   - Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   - Neither the name of Pebble nor the names of its contributors may
 *     be used to endorse or promote products derived from this software
 *     without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package net.sourceforge.pebble.domain;

import net.sourceforge.pebble.api.event.blogentry.BlogEntryEvent;
import net.sourceforge.pebble.api.event.comment.CommentEvent;
import net.sourceforge.pebble.api.event.trackback.TrackBackEvent;
import net.sourceforge.pebble.comparator.ResponseByDateComparator;
import net.sourceforge.pebble.web.validation.ValidationContext;
import net.sourceforge.pebble.trackback.TrackBackTokenManager;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.util.*;

/**
 * Represents a blog entry.
 *
 * @author Simon Brown
 */
public class BlogEntry extends PageBasedContent {

  /**
   * the log used by this class
   */
  private static Log log = LogFactory.getLog(BlogEntry.class);

  public static final String EXCERPT_PROPERTY = "excerpt";
  public static final String COMMENTS_ENABLED_PROPERTY = "commentsEnabed";
  public static final String TRACKBACKS_ENABLED_PROPERTY = "trackBacksEnabled";
  public static final String ATTACHMENT_PROPERTY = "attachment";
  public static final String CATEGORIES_PROPERTY = "categories";

  /** the permalink */
  private String permalink;

  /**
   * the category that the blog entry falls into
   */
  private Set categories = new HashSet();

  /**
   * the excerpt of the blog entry
   */
  private String excerpt = "";

  /**
   * a flag to indicate whether comments are enabled for this entry
   */
  private boolean commentsEnabled = true;

  /**
   * a flag to indicate whether TrackBacks are enabled for this entry
   */
  private boolean trackBacksEnabled = true;

  /**
   * the collection of comments for the blog entry
   */
  private List comments = new ArrayList();

  /**
   * the collection of trackbacks for the blog entry
   */
  private List trackBacks = new ArrayList();

  /** the attachment for this blog entry, if applicable */
  private Attachment attachment;

  /** the timezone that this entry was posted in */
  private String timeZoneId;

  /**
   * Creates a new blog entry.
   *
   * @param blog    the owning Blog
   */
  public BlogEntry(Blog blog) {
    super(blog);
    setPublished(false);
  }

  /**
   * Sets the title of this blog entry.
   *
   * @param newTitle  the title as a String
   */
  public void setTitle(String newTitle) {
    super.setTitle(newTitle);

    // and cause the permalink to be re-generated
    this.permalink = null;
  }

  /**
   * Gets the category of this blog entry.
   *
   * @return the category as a String
   */
  public Set<Category> getCategories() {
    return new HashSet<Category>(categories);
  }

  /**
   * Gets a list of all tags.
   *
   * @return  a List of tags
   */
  public List<Tag> getAllTags() {
    List<Tag> list = new ArrayList<Tag>();

    if (getCategories().size() > 0) {
      Iterator it = getCategories().iterator();
      while (it.hasNext()) {
        Category category = (Category)it.next();
        List tagsForCategory = category.getAllTags();
        Collections.reverse(tagsForCategory);
        Iterator jt = tagsForCategory.iterator();
        while (jt.hasNext()) {
          Tag tag = (Tag)jt.next();
          if (!list.contains(tag)) {
            list.add(tag);
          }
        }
      }
    } else {
      List tagsForCategory = getBlog().getRootCategory().getAllTags();
      Iterator it = tagsForCategory.iterator();
      while (it.hasNext()) {
        Tag tag = (Tag)it.next();
        if (!list.contains(tag)) {
          list.add(tag);
        }
      }
    }

    Iterator it = getTagsAsList().iterator();
    while (it.hasNext()) {
      Tag tag = (Tag)it.next();
      if (!list.contains(tag)) {
        list.add(tag);
      }
    }

    Collections.sort(list);
    return list;
  }

  /**
   * Sets the category of this blog entry.
   *
   * @param category the category as a String
   */
  public synchronized void addCategory(Category category) {
    if (category != null && !categories.contains(category)) {
      Set oldCategories = new HashSet(categories);
      categories.add(category);
      Set newCategories = new HashSet(categories);
      propertyChangeSupport.firePropertyChange(CATEGORIES_PROPERTY, oldCategories, newCategories);
    }
  }

  /**
   * Removes all categories from this blog entry.
   */
  public synchronized void removeAllCategories() {
    propertyChangeSupport.firePropertyChange(CATEGORIES_PROPERTY, new HashSet(categories), new HashSet());
    categories.clear();
  }

  /**
   * Sets the categories for this blog entry.
   *
   * @param newCategories   a Collection of Category instances
   */
  public synchronized void setCategories(Collection newCategories) {
    if (newCategories != null) {
      Set oldCategories = new HashSet(categories);
      categories.clear();
      Iterator it = newCategories.iterator();
      while (it.hasNext()) {
        categories.add(it.next());
      }
      propertyChangeSupport.firePropertyChange(CATEGORIES_PROPERTY, oldCategories, new HashSet(newCategories));
    }
  }

  /**
   * Determines whether this blog entry is in the specified category.
   *
   * @param category a Category instance
   * @return true if this entry is in the specified category,
   *         false otherwise
   */
  public boolean inCategory(Category category) {
    if (category != null) {
      Iterator it = categories.iterator();
      while (it.hasNext()) {
        Category c = (Category)it.next();
        if (c.equals(category) || c.hasParent(category)) {
          return true;
        }
      }

      return false;
    } else {
      return true;
    }
  }

  /**
   * Determines whether this blog entry has the specified tag.
   *
   * @param s   a String
   * @return true if this entry has the specified tag,
   *         false otherwise
   */
  public boolean hasTag(String s) {
    if (s != null) {
      return getAllTags().contains(new Tag(s, getBlog()));
    } else {
      return false;
    }
  }

  /**
   * Gets the content of this response.
   *
   * @return a String
   */
  public String getContent() {
    if (excerpt != null && excerpt.length() > 0) {
      return excerpt;
    } else {
      return getBody();
    }
  }

  /**
   * Gets the excerpt of this blog entry.
   *
   * @return the excerpt as a String
   */
  public String getExcerpt() {
    return excerpt;
  }

  /**
   * Sets the excerpt of this blog entry.
   *
   * @param newExcerpt    the excerpt as a String
   */
  public void setExcerpt(String newExcerpt) {
    if (newExcerpt != null) {
      newExcerpt = newExcerpt.trim();
    }
    propertyChangeSupport.firePropertyChange(EXCERPT_PROPERTY, excerpt, newExcerpt);
    this.excerpt = newExcerpt;
  }

  /**
   * Gets the date that this blog entry was last updated.
   *
   * @return  a Date instance representing the time of the last comment/TrackBack
   */
  public Date getLastModified() {
    Date date = getDate();

    Iterator it = comments.iterator();
    while (it.hasNext()) {
      Comment comment = (Comment)it.next();
      if (comment.getDate().after(date)) {
        date = comment.getDate();
      }
    }

    it = trackBacks.iterator();
    while (it.hasNext()) {
      TrackBack trackBack = (TrackBack)it.next();
      if (trackBack.getDate().after(date)) {
        date = trackBack.getDate();
      }
    }

    return date;
  }

  /**
   * Sets the date that this blog entry was created.
   *
   * @param newDate a java.util.Date instance
   */
  public void setDate(Date newDate) {
    super.setDate(newDate);

    // and cause the permalink to be re-generated
    this.permalink = null;
  }

  /**
   * Gets a permalink for this blog entry that is local to the blog. In other
   * words, it doesn't take into account the original permalink for
   * aggregated content.
   *
   * @return an absolute URL as a String
   */
  public String getLocalPermalink() {
    if (this.permalink == null) {
      String s = getBlog().getPermalinkProvider().getPermalink(this);
      if (s != null && s.length() > 0) {
        this.permalink = getBlog().getUrl() + s.substring(1);
      }
    }

    return permalink;
  }

  /**
   * Gets the attachment associated with this blog entry.
   *
   * @return  an Attachment instance, or null if one doesn't exist
   */
  public Attachment getAttachment() {
    return attachment;
  }

  /**
   * Sets the attachment associated with thie blog entry.
   *
   * @param newAttachment    an Attachment instance
   */

src/main/java/net/sourceforge/pebble/domain/MultiBlog.java
/*
 * Copyright (c) 2003-2011, Simon Brown
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   - Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   - Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *
 *   - Neither the name of Pebble nor the names of its contributors may
 *     be used to endorse or promote products derived from this software
 *     without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package net.sourceforge.pebble.domain;

import net.sourceforge.pebble.comparator.BlogEntryComparator;
import net.sourceforge.pebble.PebbleContext;

import javax.servlet.http.HttpServletRequest;
import java.util.*;

/**
 * A composite blog is one that is made up of one or more simple blogs. This
 * is effectively a container when Pebble is running in multi-user mode - there
 * being a single MultiBlog and many Blog instances.
 * <br /><br />
 * In addition to managing one or more simple blogs, a composite blog provides
 * some aggegration functionality over the blogs it manages in order to
 * generate an aggregated XML (RSS/RDF/Atom) feed.
 *
 * @author    Simon Brown
 */
public class MultiBlog extends AbstractBlog {

  /**
   * Creates a new Blog instance, based at the specified location.
   *
   * @param root    an absolute path pointing to the root directory of the blog
   */
  public MultiBlog(String root) {
    super(root);

    // probably MultiBlog should be made a final class if init is called from here - 
    // see javadoc comment on AbstractBlog.init() for reasons
    init();
  }

  /**
   * Gets the default properties for a MultiBlog.
   *
   * @return    a Properties instance
   */
  protected Properties getDefaultProperties() {
    Properties defaultProperties = new Properties();
    defaultProperties.setProperty(NAME_KEY, "My blogs");
    defaultProperties.setProperty(DESCRIPTION_KEY, "");
    defaultProperties.setProperty(IMAGE_KEY, "");
    defaultProperties.setProperty(AUTHOR_KEY, "Various");
    defaultProperties.setProperty(TIMEZONE_KEY, "Europe/London");
    defaultProperties.setProperty(RECENT_BLOG_ENTRIES_ON_HOME_PAGE_KEY, "3");
    defaultProperties.setProperty(LANGUAGE_KEY, "en");
    defaultProperties.setProperty(COUNTRY_KEY, "GB");
    defaultProperties.setProperty(CHARACTER_ENCODING_KEY, "UTF-8");
    defaultProperties.setProperty(THEME_KEY, "default");

    return defaultProperties;
  }

  /**
   * Gets the ID of this blog.
   *
   * @return the ID as a String
   */
  public String getId() {
    return "";
  }

  /**
   * Gets the URL where this blog is deployed.
   *
   * @return a URL as a String
   */
  public String getSecureUrl() {
    return PebbleContext.getInstance().getConfiguration().getSecureUrl();
  }
  /**
   * Gets the URL where this blog is deployed.
   *
   * @return a URL as a String
   */
  public String getUrl() {
    return PebbleContext.getInstance().getConfiguration().getUrl();
  }

  /**
   * Gets the relative URL where this blog is deployed.
   *
   * @return a URL as a String
   */
  public String getRelativeUrl() {
    return "/";
  }

  /**
   * Gets the date that this blog was last updated.
   *
   * @return  a Date instance representing the time of the most recent entry
   */
  public Date getLastModified() {
    Date date = new Date(0);

    Iterator it = BlogManager.getInstance().getPublicBlogs().iterator();
    Blog blog;
    while (it.hasNext()) {
      blog = (Blog)it.next();
      if (blog.getLastModified().after(date)) {
        date = blog.getLastModified();
      }
    }

    return date;
  }

  /**
   * Gets the most recent blog entries, the number
   * of which is specified.
   *
   * @param numberOfEntries the number of entries to get
   * @return a List containing the most recent blog entries
   */
  public List<BlogEntry> getRecentBlogEntries(int numberOfEntries) {
    List<BlogEntry> blogEntries = new ArrayList<BlogEntry>();

    for (Blog blog : BlogManager.getInstance().getPublicBlogs()) {
      blogEntries.addAll(blog.getRecentPublishedBlogEntries());
    }

    Collections.sort(blogEntries, new BlogEntryComparator());

    if (blogEntries.size() >= numberOfEntries) {
      return new ArrayList<BlogEntry>(blogEntries).subList(0, numberOfEntries);
    } else {
      return new ArrayList<BlogEntry>(blogEntries);
    }
  }

  /**
   * Logs this request for blog.
   *
   * @param request   the HttpServletRequest instance for this request
   */
  public void log(HttpServletRequest request, int status) {
    // no op
  }

}

src/main/webapp/WEB-INF/jsp/blogEntry.jsp
<%--
  renders a single blog entry
--%>
<c:choose>
  <c:when test="${blogEntry.unpublished}">
<div class="contentItem unpublished">
  </c:when>
  <c:otherwise>
<div class="contentItem published">
  </c:otherwise>
</c:choose>

  <%@ include file="/WEB-INF/fragments/blogEntryLinks.jspf" %>

  <a name="a${blogEntry.id}"></a>
  <h1 class="contentItemTitle"><a href="${url:rewrite(blogEntry.permalink)}">${blogEntry.title}</a></h1>
  <h2 class="contentItemSubtitle">${blogEntry.subtitle}</h2>

  <div class="contentItemBody">
    <c:choose>
      <c:when test="${displayMode == 'detail'}">
        <%-- here the blog entry is being shown on its own page --%>
        <c:out value="${blogEntry.body}" escapeXml="false" />
      </c:when>
      <c:when test="${displayMode == 'preview'}">
        <%-- this is the blog entry preview, where both excerpt and body need to be shown --%>
        <c:if test="${not empty blogEntry.excerpt}">
        <p><b>Excerpt</b></p><c:out value="${blogEntry.excerpt}" escapeXml="false" />
        </c:if>
        <c:if test="${not empty blogEntry.body}">
        <p><b>Body</b></p><c:out value="${blogEntry.body}" escapeXml="false" />
        </c:if>
      </c:when>
      <c:otherwise>
        <c:choose>
          <c:when test="${empty blogEntry.excerpt}">
            <%-- there is no excerpt, so show the body --%>
            <c:out value="${blogEntry.body}" escapeXml="false" />
          </c:when>
          <c:otherwise>
            <%-- an excerpt is present, so show this --%>
            <c:out value="${blogEntry.excerpt}" escapeXml="false" />
          </c:otherwise>
        </c:choose>
      </c:otherwise>
    </c:choose>

    <div class="metadata">
      <%@ include file="/WEB-INF/fragments/responseLinks.jspf" %>
      <c:choose>
        <c:when test="${not empty blogEntry.user.website}"><c:set var="author" value='<a href="${blogEntry.user.website}">${blogEntry.user.name}</a>'/></c:when>
        <c:when test="${not empty blogEntry.user and not empty blogEntry.user.profile}"><c:set var="author" value='<a href="authors/${blogEntry.user.username}/">${blogEntry.user.name}</a>'/></c:when>
        <c:when test="${not empty blogEntry.user}"><c:set var="author" value='<a href="authors/${blogEntry.author}/">${blogEntry.user.name}</a>'/></c:when>
        <c:otherwise><c:set var="author" value='<a href="advancedSearch.action?author=${blogEntry.author}">${blogEntry.author}</a>'/></c:otherwise>
      </c:choose>
      <fmt:formatDate var="blogEntryDate" scope="page" value="${blogEntry.date}" timeZone="${blogEntry.timeZoneId}" type="both" dateStyle="long" timeStyle="long"/>
      <fmt:message key="blogentry.from">
        <fmt:param value="${author}"/>
        <fmt:param>
        ${blogEntryDate}
        </fmt:param>
      </fmt:message>
      <a href="${url:rewrite(blogEntry.localPermalink)}" title="${blogEntry.localPermalink}">#</a>
      <c:if test="${not empty blogEntry.attachment}"><a href="${url:rewrite(blogEntry.attachment.url)}" title="${blogEntry.attachment.size} bytes, ${blogEntry.attachment.type}"><fmt:message key="blogentry.attachment" /></a></c:if>
    </div>
  </div>

  <c:if test="${displayMode == 'detail'}">

    <pebble:isBlogContributor>
    <c:if test="${blogEntry.numberOfResponses > 0}">
    <form name="responsesForm" method="post" action="manageResponses.secureaction">
      <pebble:token/>
    <input type="hidden" name="redirectUrl" value="${url:rewrite(blogEntry.localPermalink)}" />
    </c:if>
    </pebble:isBlogContributor>

    <a name="responses"></a>
    <jsp:include page="/WEB-INF/jsp/comments.jsp"/>
    <jsp:include page="/WEB-INF/jsp/trackbacks.jsp"/>

    <pebble:isBlogContributor>
    <c:if test="${blogEntry.numberOfResponses > 0}">
    <table width="99%" cellspacing="0" cellpadding="0">
      <tr>
        <td align="left">
          <input type="button" value="Check All" onclick="checkAll(document.responsesForm.response)" />
          <input type="button" value="Uncheck All" onclick="uncheckAll(document.responsesForm.response)" />
        </td>
        <td align="right">
          <button type="submit" name="submit" value="Approve" ><fmt:message key="common.approve"/></button>
          <button type="submit" name="submit" value="Reject" ><fmt:message key="common.reject"/></button>
          <button type="submit" name="submit" value="Remove" ><fmt:message key="common.remove"/></button>
        </td>
      </tr>
    </table>
    </form>
    </c:if>
    </pebble:isBlogContributor>

    <div align="center" class="commentsAndTrackbacks">
      <c:if test="${blogEntry.commentsEnabled}">
        <a href="javascript: showCommentForm();"><fmt:message key="comment.addComment"/></a>
      </c:if>
      <c:if test="${blogEntry.trackBacksEnabled}">
        <a href="generateTrackBackLink.action?entry=${blogEntry.id}"><fmt:message key="trackback.sendTrackBack"/></a>
      </c:if>
    </div>

    <div id="commentFormDiv" style="display:none;"><%@ include file="/WEB-INF/fragments/commentForm.jsp" %></div>

  </c:if>

</div>

src/main/webapp/WEB-INF/jsp/removeEmailAddress.jsp
<div class="contentItem">

  <h1><fmt:message key="comment.removeEmailAddressTitle" /></h1>
  <h2>&nbsp;</h2>

  <div class="contentItemBody">
    <fmt:message key="comment.removeEmailAddress" />
    <br /><br />

    <form name="removeEmailAddress" action="removeEmailAddress.action" method="POST">
    <pebble:token/>
    <input type="hidden" name="entry" value=""${blogEntry.id}" />
    <input type="text" name="email" size="40" />
    <input name="submit" type="submit" Value="<fmt:message key="comment.removeEmailAddressButton" />" />
    </form>

    <p>
      <fmt:message key="common.backTo" /> <a href="${url:rewrite(blogEntry.permalink)}">${blogEntry.title}</a>.
    </p>
  </div>
</div>

src/main/webapp/WEB-INF/jsp/trackBackSent.jsp
<div class="contentItem">
  <h1>TrackBack</h1>
  <h2>&nbsp;</h2>

  <div class="contentItemBody">
    TrackBack sent to ${trackBackUrl}, response code ${trackBackResponseCode}
    <br />
    <pre><c:out value="${trackBackResponseMessage}" escapeXml="true" /></pre>

    <p>
    Return to <a href="${url:rewrite(blogEntry.permalink)}">${blogEntry.title}</a>.
    </p>
  </div>

</div>

src/main/webapp/WEB-INF/jsp/trackback.jsp
<%--
  renders a single TrackBack
--%>
<c:choose>
  <c:when test="${trackback.pending}">
<div class="response pending">
  </c:when>
  <c:when test="${trackback.rejected}">
<div class="response rejected">
  </c:when>
  <c:otherwise>
<div class="response approved">
  </c:otherwise>
</c:choose>

  <%@ include file="/WEB-INF/fragments/trackbackLinks.jspf" %>

  <h1>
    <a name="trackback${trackback.id}"></a>${trackback.title}
  </h1>

  <div class="metadata">
    <c:set var="trackbackAuthor" scope="page">
      ${trackback.blogName}
      <pebble:isAuthorisedForBlog>
      (${trackback.ipAddress})
      </pebble:isAuthorisedForBlog>
    </c:set>
    <fmt:formatDate var="trackbackDate" scope="page" value="${trackback.date}" timeZone="${blogEntry.timeZoneId}" type="both" dateStyle="long" timeStyle="long"/>

    <fmt:message key="trackback.from">
      <fmt:param>
        ${trackbackAuthor}
      </fmt:param>
      <fmt:param value="${trackbackDate}"/>
    </fmt:message>
    <a href="${url:rewrite(trackback.permalink)}" title="${trackback.permalink}">#</a>
  </div>

  <div class="responseBody">
    <c:out value="${trackback.excerpt}" escapeXml="false"/>
  </div>

</div>

src/main/webapp/WEB-INF/jsp/viewReferers.jsp
<div class="contentItem">

  <div class="contentItemLinks">
    <a href="./help/referers.html" target="_blank"><fmt:message key="common.help"/></a>
  </div>

  <h1>
  	<fmt:message key="view.referrersForPeriod">
	  <fmt:param>${logPeriod}</fmt:param>
	</fmt:message>
  </h1>
  <h2>Total : <fmt:formatNumber value="${totalReferers}"/></h2>

  <div class="contentItemBody">
    <form name="referersForm" method="post" action="addRefererFilters.secureaction">
    <pebble:token/>
    <input type="hidden" name="redirectUrl" value="${blogUrl}/viewReferers.secureaction" />
    <input type="hidden" name="year" value="<fmt:formatNumber value="${param.year}" pattern="#"/>" />
    <input type="hidden" name="month" value="<fmt:formatNumber value="${param.month}"/>" />
    <input type="hidden" name="day" value="<fmt:formatNumber value="${param.day}"/>" />

    <table width="99%" cellspacing="0" cellpadding="4">
      <thead>
        <tr>
          <th><input type="checkbox" name="allExpressions" onclick="toggleCheckAll(document.referersForm.allExpressions, document.referersForm.expression)"/></th>
          <th>Referer</th>
          <th align="right">Count</th>
        </tr>
      </thead>
      <tbody>
      <c:forEach var="referer" items="${referers}" varStatus="status">
        <c:choose>
          <c:when test="${status.count % 2 == 0}">
            <tr class="even small">
          </c:when>
          <c:otherwise>
              <tr class="odd small">
          </c:otherwise>
        </c:choose>
          <td width="2%">
            <input type="checkbox" name="expression" value="${referer.domainFilter}" />
          </td>
          <td>
            <a href="${fn:escapeXml(referer.url)}" title="${fn:escapeXml(referer.url)}" rel="nofollow">${fn:escapeXml(referer.truncatedName)}</a>
          </td>
          <td align="right">
            <fmt:formatNumber value="${referer.count}"/>
          </td>
        </tr>
      </c:forEach>
      </tbody>
    </table>

    <pebble:isAuthorisedForBlog>
    <br />

    <table width="99%" cellspacing="0" cellpadding="0">
      <tr>
        <td align="right">
          <input type="submit" value="Spam" />
        </td>
      </tr>
    </table>
    </pebble:isAuthorisedForBlog>

    </form>
  </div>

</div>

src/main/webapp/WEB-INF/jsp/viewRequestsByHour.jsp
<div class="contentItem">

  <div class="contentItemLinks">
    <a href="./help/logs.html" target="_blank">Help</a>
  </div>

  <h1>Requests by Hour for <c:out value="${logPeriod}"/></h1>
  <h2>&nbsp;</h2>

  <div class="contentItemBody">
    <table width="99%" cellspacing="0" cellpadding="4">
      <thead>
        <tr>
          <th>Hour of Day (${blog.timeZoneId})</th>
          <th align="right">Requests</th>
          <th align="right">Unique</th>
        </tr>
      </thead>
      <tbody>
        <c:forEach var="count" begin="0" end="23">
          <c:choose>
            <c:when test="${count % 2 == 0}">
              <tr class="even small">
            </c:when>
            <c:otherwise>
                <tr class="odd small">
            </c:otherwise>
          </c:choose>
          <td><fmt:formatNumber value="${count}" pattern="00"/>:00</td>
          <td align="right"><fmt:formatNumber value="${requestsPerHour[count]}"/></td>
          <td align="right"><fmt:formatNumber value="${uniqueIpsPerHour[count]}"/></td>
        </tr>
        </c:forEach>
    </tbody>
    </table>
  </div>

</div>